name: upower
adopt-info: upower
summary: An abstraction for power devices
description: |
    UPower is an abstraction for enumerating power devices, listening
    to device events and querying history and statistics.
confinement: strict
base: core24

slots:
  upower-dbus:
    interface: dbus
    bus: system
    name: org.freedesktop.UPower

  upower:
    interface: upower-observe

plugs:
  upower-client:
    interface: upower-observe

apps:
  upowerd:
    command: usr/libexec/upowerd
    daemon: dbus
    daemon-scope: system
    activates-on:
      - upower-dbus
    slots:
      - upower
    plugs:
      - hardware-observe
      - bluez

  upower:
    command: usr/bin/upower
    plugs:
      - upower-client

layout:
  /etc/UPower:
    bind: $SNAP/etc/UPower

parts:
  upower-copyright:
    plugin: nil
    stage-packages:
      - upower
      - libupower-glib3
    stage:
      - usr/share/doc/libupower-glib3/copyright
      - usr/share/doc/libupower-glib3/changelog.*
      - usr/share/doc/upower/copyright
      - usr/share/doc/upower/changelog.*

  upower:
    build-packages:
    - meson
    - libglib2.0-dev
    - xsltproc
    - libgudev-1.0-dev
    - gtk-doc-tools
    stage-packages:
    - libgudev-1.0-0
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source-type: git
    source-branch: applied/ubuntu/noble
    source: https://git.launchpad.net/ubuntu/+source/upower
    override-pull: |
      craftctl default
      version="$(cd "${CRAFT_PART_SRC}"; dpkg-parsechangelog -SVersion)"
      craftctl set version="${version}"
