snapcraft-version: 8.14.5.post106
snapcraft-started-at: '2026-04-27T20:19:57.728663Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '26.04'
name: upower
version: 1.91.1-1
summary: An abstraction for power devices
description: |
  UPower is an abstraction for enumerating power devices, listening
  to device events and querying history and statistics.
base: core26
grade: stable
confinement: strict
apps:
  upowerd:
    command: usr/libexec/upowerd
    daemon: dbus
    slots:
    - upower
    plugs:
    - hardware-observe
    - bluez
    daemon-scope: system
    activates-on:
    - upower-dbus
  upower:
    command: usr/bin/upower
    plugs:
    - upower-client
parts:
  upower-copyright:
    plugin: nil
    stage-packages:
    - libgudev-1.0-0=1:238-7build1
    - libimobiledevice-1.0-6=1.4.0-1build1
    - libimobiledevice-glue-1.0-0=1.3.2-2build1
    - libplist-2.0-4=2.7.0+git20250820-1build1
    - libupower-glib3=1.91.1-1
    - libusbmuxd-2.0-7=2.1.1-1
    - upower=1.91.1-1
    stage:
    - usr/share/doc/libupower-glib3/copyright
    - usr/share/doc/libupower-glib3/changelog.*
    - usr/share/doc/upower/copyright
    - usr/share/doc/upower/changelog.*
    prime: []
    build-packages: []
  upower:
    build-packages:
    - meson
    - libgudev-1.0-dev
    - systemd-dev
    stage-packages:
    - libgudev-1.0-0=1:238-7build1
    plugin: meson
    meson-parameters:
    - --prefix=/usr
    - -Dgtk-doc=false
    - -Dman=false
    source-type: git
    source-branch: applied/ubuntu/resolute-proposed
    source: https://git.launchpad.net/ubuntu/+source/upower
    stage: []
    prime: []
architectures:
- armhf
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/+snap/upower-snap-26/+build/3134604
build-packages: []
build-snaps: []
primed-stage-packages:
- libgudev-1.0-0=1:238-7build1
- libupower-glib3=1.91.1-1
- upower=1.91.1-1
