name: Publish to edge

on:
  push:
    branches:
      - snap-22

jobs:
  publish_to_edge:
    # self-hosted runner so we can access launchpad
    runs-on: [self-hosted, spread-enabled]
    environment: store
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: canonical/system-snaps-cicd-tools/action-publish-edge@main
        with:
          # TODO: remove this filter when launchpad riscv64 builds are stable
          architectures: arm64,amd64,armhf
