name: Publish to edge

on:
  push:
    branches:
      - main

jobs:
  publish_to_edge:
    # self-hosted runner so we can access launchpad
    runs-on: self-hosted
    environment: beta
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: canonical/system-snaps-cicd-tools/action-publish-edge@main
