name: Release snap

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build_release:
    runs-on: self-hosted
    environment: beta
    steps:
      - name: Build release
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: canonical/system-snaps-cicd-tools/action-release@main
