name: Release snap

on:
  workflow_dispatch:
    branches:
      - snap-22

jobs:
  build_release:
    runs-on: [self-hosted, spread-enabled]
    environment: store
    steps:
      - name: Build release
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: canonical/system-snaps-cicd-tools/action-release@main
        with:
          # TODO: remove this filter when launchpad riscv64 builds are stable
          architectures: arm64,amd64,armhf
